services:
  postgres:
    image: postgres:16-alpine
    container_name: gerenciamento-felinos-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: felino
      POSTGRES_PASSWORD: felino
      POSTGRES_DB: gerenciamento_felinos
    ports:
      - "5432:5432"
    volumes:
      - felino_pgdata:/var/lib/postgresql/data

volumes:
  felino_pgdata:
